#!/usr/bin/env python3
"""
Regenerates the project cards on studio/index.html by scanning immediate
subfolders for an index.html that declares:

  <meta name="studio:project" content="Project Name">
  <meta name="studio:description" content="One-line description.">

Folders without those two meta tags are skipped, so draft/private folders
stay off the index until they opt in.

Run manually after adding a project:

  python3 generate-index.py

Or wire it up as a Cloudflare Pages build command (Settings > Builds &
deployments > Build command) so the index regenerates on every deploy.
Build output directory stays "/" — this script only rewrites index.html
in place before Pages serves the folder.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX_FILE = ROOT / "index.html"
START_MARKER = "<!-- STUDIO:CARDS:START"
END_MARKER = "<!-- STUDIO:CARDS:END -->"
START_COMMENT = START_MARKER + " — auto-generated by generate-index.py, do not hand-edit between these markers -->"

META_RE = re.compile(
    r'<meta\s+name=["\']studio:(?P<key>project|description)["\']\s+content=["\'](?P<value>[^"\']*)["\']',
    re.IGNORECASE,
)

SKIP_DIRS = {"assets", "css", "js", "images", "node_modules", ".git", ".wrangler"}


def find_projects():
    projects = []
    for entry in sorted(ROOT.iterdir()):
        if not entry.is_dir() or entry.name in SKIP_DIRS or entry.name.startswith("."):
            continue
        index = entry / "index.html"
        if not index.exists():
            continue
        html = index.read_text(encoding="utf-8", errors="ignore")
        meta = {m.group("key"): m.group("value") for m in META_RE.finditer(html)}
        if "project" not in meta:
            continue  # opt-in only — no meta tag, no card
        projects.append({
            "slug": entry.name,
            "title": meta["project"],
            "description": meta.get("description", ""),
        })
    projects.sort(key=lambda p: p["title"].lower())
    return projects


def render_block(projects):
    indent = "        "
    lines = [START_COMMENT]
    for i, p in enumerate(projects):
        if i > 0:
            lines.append("")
        lines.append(f'<a class="card" href="/{p["slug"]}/">')
        lines.append(f'  <strong>{p["title"]}</strong>')
        if p["description"]:
            lines.append(f'  <span>{p["description"]}</span>')
        lines.append("</a>")
    lines.append(END_MARKER)
    return ("\n" + indent).join(lines)


def main():
    projects = find_projects()
    html = INDEX_FILE.read_text(encoding="utf-8")

    start = html.find(START_MARKER)
    end = html.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            "Could not find STUDIO:CARDS markers in index.html. "
            "Add <!-- STUDIO:CARDS:START --> ... <!-- STUDIO:CARDS:END --> around the grid contents."
        )
    end += len(END_MARKER)

    new_html = html[:start] + render_block(projects) + html[end:]
    INDEX_FILE.write_text(new_html, encoding="utf-8")

    print(f"Updated index.html with {len(projects)} project(s):")
    for p in projects:
        print(f"  - {p['title']} -> /{p['slug']}/")


if __name__ == "__main__":
    main()
