#!/usr/bin/env node
/* ========================================================================== */
/* II COMMANDMENTS — verse fetcher                                            */
/* Pulls public-domain Bible text from bible-api.com and writes verses.js     */
/* (window.TC_VERSES). Run: node scripts/fetch-verses.mjs                     */
/* Licensed versions (CSB, NIV, ESV) are NOT fetched here — see PROJECT_PLAN. */
/* ========================================================================== */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'verses.js');
const VERSIONS = ['web', 'kjv', 'asv'];

/* ref id → bible-api.com query. Ids are what data-ref uses in the HTML. */
const REFS = {
	'matthew.22.36-40': 'Matthew 22:36-40',
	'mark.12.28-34':    'Mark 12:28-34',
	'luke.10.25-37':    'Luke 10:25-37',
	'john.13.34-35':    'John 13:34-35',
	'john.14.15':       'John 14:15',
	'matthew.22.40':    'Matthew 22:40',
	'matthew.22.37-40': 'Matthew 22:37-40',
	'1timothy.6.11-16': '1 Timothy 6:11-16',
	'matthew.5.43-48':  'Matthew 5:43-48',
	'matthew.5.17-20':  'Matthew 5:17-20',
	'john.15.9-17':     'John 15:9-17',
	'romans.13.8-10':   'Romans 13:8-10',
	'galatians.5.13-14':'Galatians 5:13-14',
	'james.2.8':        'James 2:8',
	'1john.4.7-12':     '1 John 4:7-12',
	'1john.4.19-21':    '1 John 4:19-21',
	'matthew.28.19-20': 'Matthew 28:19-20',
	'mark.16.15':       'Mark 16:15'
};

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function fetchRef(query, version, attempt = 1) {
	const url = `https://bible-api.com/${encodeURIComponent(query)}?translation=${version}`;
	const res = await fetch(url);
	if (res.status === 429 && attempt <= 5) { /* free API rate-limits; back off and retry */
		const wait = 2000 * attempt;
		process.stdout.write(`429, waiting ${wait / 1000}s … `);
		await sleep(wait);
		return fetchRef(query, version, attempt + 1);
	}
	if (!res.ok) throw new Error(`${res.status} ${url}`);
	const json = await res.json();
	return {
		reference: json.reference,
		verses: json.verses.map(v => ({ n: v.verse, text: v.text.replace(/\s+/g, ' ').trim() }))
	};
}

const out = {};
for (const version of VERSIONS) {
	out[version] = {};
	for (const [id, query] of Object.entries(REFS)) {
		process.stdout.write(`${version} ${query} … `);
		out[version][id] = await fetchRef(query, version);
		console.log(`${out[version][id].verses.length} verses`);
		await sleep(1200); /* be polite to the free API */
	}
}

const banner = `/* ========================================================================== */
/* II COMMANDMENTS — verse text (GENERATED by scripts/fetch-verses.mjs)       */
/* Public-domain versions from bible-api.com. Do not hand-edit; re-run script. */
/* Shape: TC_VERSES[version][refId] → { reference, verses:[{ n, text }] }     */
/* ========================================================================== */
`;
writeFileSync(OUT, banner + 'window.TC_VERSES = ' + JSON.stringify(out, null, '\t') + ';\n');
console.log(`\nwrote ${OUT}`);
