/* ========================================================================== */
/* II COMMANDMENTS — verse text (GENERATED by scripts/fetch-verses.mjs)       */
/* Public-domain versions from bible-api.com. Do not hand-edit; re-run script. */
/* Shape: TC_VERSES[version][refId] → { reference, verses:[{ n, text }] }     */
/* ========================================================================== */
window.TC_VERSES = {
	"web": {
		"matthew.22.36-40": {
			"reference": "Matthew 22:36-40",
			"verses": [
				{
					"n": 36,
					"text": "“Teacher, which is the greatest commandment in the law?”"
				},
				{
					"n": 37,
					"text": "Jesus said to him, “‘You shall love the Lord your God with all your heart, with all your soul, and with all your mind.’"
				},
				{
					"n": 38,
					"text": "This is the first and great commandment."
				},
				{
					"n": 39,
					"text": "A second likewise is this, ‘You shall love your neighbor as yourself.’"
				},
				{
					"n": 40,
					"text": "The whole law and the prophets depend on these two commandments.”"
				}
			]
		},
		"mark.12.28-34": {
			"reference": "Mark 12:28-34",
			"verses": [
				{
					"n": 28,
					"text": "One of the scribes came, and heard them questioning together. Knowing that he had answered them well, asked him, “Which commandment is the greatest of all?”"
				},
				{
					"n": 29,
					"text": "Jesus answered, “The greatest is, ‘Hear, Israel, the Lord our God, the Lord is one:"
				},
				{
					"n": 30,
					"text": "you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength.’ This is the first commandment."
				},
				{
					"n": 31,
					"text": "The second is like this, ‘You shall love your neighbor as yourself.’ There is no other commandment greater than these.”"
				},
				{
					"n": 32,
					"text": "The scribe said to him, “Truly, teacher, you have said well that he is one, and there is none other but he,"
				},
				{
					"n": 33,
					"text": "and to love him with all the heart, and with all the understanding, with all the soul, and with all the strength, and to love his neighbor as himself, is more important than all whole burnt offerings and sacrifices.”"
				},
				{
					"n": 34,
					"text": "When Jesus saw that he answered wisely, he said to him, “You are not far from God’s Kingdom.” No one dared ask him any question after that."
				}
			]
		},
		"luke.10.25-37": {
			"reference": "Luke 10:25-37",
			"verses": [
				{
					"n": 25,
					"text": "Behold, a certain lawyer stood up and tested him, saying, “Teacher, what shall I do to inherit eternal life?”"
				},
				{
					"n": 26,
					"text": "He said to him, “What is written in the law? How do you read it?”"
				},
				{
					"n": 27,
					"text": "He answered, “You shall love the Lord your God with all your heart, with all your soul, with all your strength, and with all your mind; and your neighbor as yourself.”"
				},
				{
					"n": 28,
					"text": "He said to him, “You have answered correctly. Do this, and you will live.”"
				},
				{
					"n": 29,
					"text": "But he, desiring to justify himself, asked Jesus, “Who is my neighbor?”"
				},
				{
					"n": 30,
					"text": "Jesus answered, “A certain man was going down from Jerusalem to Jericho, and he fell among robbers, who both stripped him and beat him, and departed, leaving him half dead."
				},
				{
					"n": 31,
					"text": "By chance a certain priest was going down that way. When he saw him, he passed by on the other side."
				},
				{
					"n": 32,
					"text": "In the same way a Levite also, when he came to the place, and saw him, passed by on the other side."
				},
				{
					"n": 33,
					"text": "But a certain Samaritan, as he traveled, came where he was. When he saw him, he was moved with compassion,"
				},
				{
					"n": 34,
					"text": "came to him, and bound up his wounds, pouring on oil and wine. He set him on his own animal, and brought him to an inn, and took care of him."
				},
				{
					"n": 35,
					"text": "On the next day, when he departed, he took out two denarii, and gave them to the host, and said to him, ‘Take care of him. Whatever you spend beyond that, I will repay you when I return.’"
				},
				{
					"n": 36,
					"text": "Now which of these three do you think seemed to be a neighbor to him who fell among the robbers?”"
				},
				{
					"n": 37,
					"text": "He said, “He who showed mercy on him.” Then Jesus said to him, “Go and do likewise.”"
				}
			]
		},
		"john.13.34-35": {
			"reference": "John 13:34-35",
			"verses": [
				{
					"n": 34,
					"text": "A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another."
				},
				{
					"n": 35,
					"text": "By this everyone will know that you are my disciples, if you have love for one another.”"
				}
			]
		},
		"john.14.15": {
			"reference": "John 14:15",
			"verses": [
				{
					"n": 15,
					"text": "If you love me, keep my commandments."
				}
			]
		},
		"matthew.22.40": {
			"reference": "Matthew 22:40",
			"verses": [
				{
					"n": 40,
					"text": "The whole law and the prophets depend on these two commandments.”"
				}
			]
		},
		"matthew.22.37-40": {
			"reference": "Matthew 22:37-40",
			"verses": [
				{
					"n": 37,
					"text": "Jesus said to him, “‘You shall love the Lord your God with all your heart, with all your soul, and with all your mind.’"
				},
				{
					"n": 38,
					"text": "This is the first and great commandment."
				},
				{
					"n": 39,
					"text": "A second likewise is this, ‘You shall love your neighbor as yourself.’"
				},
				{
					"n": 40,
					"text": "The whole law and the prophets depend on these two commandments.”"
				}
			]
		},
		"1timothy.6.11-16": {
			"reference": "1 Timothy 6:11-16",
			"verses": [
				{
					"n": 11,
					"text": "But you, man of God, flee these things, and follow after righteousness, godliness, faith, love, perseverance, and gentleness."
				},
				{
					"n": 12,
					"text": "Fight the good fight of faith. Take hold of the eternal life to which you were called, and you confessed the good confession in the sight of many witnesses."
				},
				{
					"n": 13,
					"text": "I command you before God, who gives life to all things, and before Christ Jesus, who before Pontius Pilate testified the good confession,"
				},
				{
					"n": 14,
					"text": "that you keep the commandment without spot, blameless, until the appearing of our Lord Jesus Christ;"
				},
				{
					"n": 15,
					"text": "which in its own times he will show, who is the blessed and only Ruler, the King of kings, and Lord of lords;"
				},
				{
					"n": 16,
					"text": "who alone has immortality, dwelling in unapproachable light; whom no man has seen, nor can see: to whom be honor and eternal power. Amen."
				}
			]
		},
		"matthew.5.43-48": {
			"reference": "Matthew 5:43-48",
			"verses": [
				{
					"n": 43,
					"text": "“You have heard that it was said, ‘You shall love your neighbor and hate your enemy.’"
				},
				{
					"n": 44,
					"text": "But I tell you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who mistreat you and persecute you,"
				},
				{
					"n": 45,
					"text": "that you may be children of your Father who is in heaven. For he makes his sun to rise on the evil and the good, and sends rain on the just and the unjust."
				},
				{
					"n": 46,
					"text": "For if you love those who love you, what reward do you have? Don’t even the tax collectors do the same?"
				},
				{
					"n": 47,
					"text": "If you only greet your friends, what more do you do than others? Don’t even the tax collectors do the same?"
				},
				{
					"n": 48,
					"text": "Therefore you shall be perfect, just as your Father in heaven is perfect."
				}
			]
		},
		"matthew.5.17-20": {
			"reference": "Matthew 5:17-20",
			"verses": [
				{
					"n": 17,
					"text": "“Don’t think that I came to destroy the law or the prophets. I didn’t come to destroy, but to fulfill."
				},
				{
					"n": 18,
					"text": "For most certainly, I tell you, until heaven and earth pass away, not even one smallest letter or one tiny pen stroke shall in any way pass away from the law, until all things are accomplished."
				},
				{
					"n": 19,
					"text": "Whoever, therefore, shall break one of these least commandments, and teach others to do so, shall be called least in the Kingdom of Heaven; but whoever shall do and teach them shall be called great in the Kingdom of Heaven."
				},
				{
					"n": 20,
					"text": "For I tell you that unless your righteousness exceeds that of the scribes and Pharisees, there is no way you will enter into the Kingdom of Heaven."
				}
			]
		},
		"john.15.9-17": {
			"reference": "John 15:9-17",
			"verses": [
				{
					"n": 9,
					"text": "Even as the Father has loved me, I also have loved you. Remain in my love."
				},
				{
					"n": 10,
					"text": "If you keep my commandments, you will remain in my love; even as I have kept my Father’s commandments, and remain in his love."
				},
				{
					"n": 11,
					"text": "I have spoken these things to you, that my joy may remain in you, and that your joy may be made full."
				},
				{
					"n": 12,
					"text": "“This is my commandment, that you love one another, even as I have loved you."
				},
				{
					"n": 13,
					"text": "Greater love has no one than this, that someone lay down his life for his friends."
				},
				{
					"n": 14,
					"text": "You are my friends, if you do whatever I command you."
				},
				{
					"n": 15,
					"text": "No longer do I call you servants, for the servant doesn’t know what his lord does. But I have called you friends, for everything that I heard from my Father, I have made known to you."
				},
				{
					"n": 16,
					"text": "You didn’t choose me, but I chose you, and appointed you, that you should go and bear fruit, and that your fruit should remain; that whatever you will ask of the Father in my name, he may give it to you."
				},
				{
					"n": 17,
					"text": "“I command these things to you, that you may love one another."
				}
			]
		},
		"romans.13.8-10": {
			"reference": "Romans 13:8-10",
			"verses": [
				{
					"n": 8,
					"text": "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law."
				},
				{
					"n": 9,
					"text": "For the commandments, “You shall not commit adultery,” “You shall not murder,” “You shall not steal,” “You shall not covet,” and whatever other commandments there are, are all summed up in this saying, namely, “You shall love your neighbor as yourself.”"
				},
				{
					"n": 10,
					"text": "Love doesn’t harm a neighbor. Love therefore is the fulfillment of the law."
				}
			]
		},
		"galatians.5.13-14": {
			"reference": "Galatians 5:13-14",
			"verses": [
				{
					"n": 13,
					"text": "For you, brothers, were called for freedom. Only don’t use your freedom for gain to the flesh, but through love be servants to one another."
				},
				{
					"n": 14,
					"text": "For the whole law is fulfilled in one word, in this: “You shall love your neighbor as yourself.”"
				}
			]
		},
		"james.2.8": {
			"reference": "James 2:8",
			"verses": [
				{
					"n": 8,
					"text": "However, if you fulfill the royal law, according to the Scripture, “You shall love your neighbor as yourself,” you do well."
				}
			]
		},
		"1john.4.7-12": {
			"reference": "1 John 4:7-12",
			"verses": [
				{
					"n": 7,
					"text": "Beloved, let us love one another, for love is of God; and everyone who loves has been born of God, and knows God."
				},
				{
					"n": 8,
					"text": "He who doesn’t love doesn’t know God, for God is love."
				},
				{
					"n": 9,
					"text": "By this God’s love was revealed in us, that God has sent his one and only Son into the world that we might live through him."
				},
				{
					"n": 10,
					"text": "In this is love, not that we loved God, but that he loved us, and sent his Son as the atoning sacrifice for our sins."
				},
				{
					"n": 11,
					"text": "Beloved, if God loved us in this way, we also ought to love one another."
				},
				{
					"n": 12,
					"text": "No one has seen God at any time. If we love one another, God remains in us, and his love has been perfected in us."
				}
			]
		},
		"1john.4.19-21": {
			"reference": "1 John 4:19-21",
			"verses": [
				{
					"n": 19,
					"text": "We love him, because he first loved us."
				},
				{
					"n": 20,
					"text": "If a man says, “I love God,” and hates his brother, he is a liar; for he who doesn’t love his brother whom he has seen, how can he love God whom he has not seen?"
				},
				{
					"n": 21,
					"text": "This commandment we have from him, that he who loves God should also love his brother."
				}
			]
		},
		"matthew.28.19-20": {
			"reference": "Matthew 28:19-20",
			"verses": [
				{
					"n": 19,
					"text": "Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,"
				},
				{
					"n": 20,
					"text": "teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age.” Amen."
				}
			]
		},
		"mark.16.15": {
			"reference": "Mark 16:15",
			"verses": [
				{
					"n": 15,
					"text": "He said to them, “Go into all the world, and preach the Good News to the whole creation."
				}
			]
		}
	},
	"kjv": {
		"matthew.22.36-40": {
			"reference": "Matthew 22:36-40",
			"verses": [
				{
					"n": 36,
					"text": "Master, which is the great commandment in the law?"
				},
				{
					"n": 37,
					"text": "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."
				},
				{
					"n": 38,
					"text": "This is the first and great commandment."
				},
				{
					"n": 39,
					"text": "And the second is like unto it, Thou shalt love thy neighbour as thyself."
				},
				{
					"n": 40,
					"text": "On these two commandments hang all the law and the prophets."
				}
			]
		},
		"mark.12.28-34": {
			"reference": "Mark 12:28-34",
			"verses": [
				{
					"n": 28,
					"text": "And one of the scribes came, and having heard them reasoning together, and perceiving that he had answered them well, asked him, Which is the first commandment of all?"
				},
				{
					"n": 29,
					"text": "And Jesus answered him, The first of all the commandments is, Hear, O Israel; The Lord our God is one Lord:"
				},
				{
					"n": 30,
					"text": "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment."
				},
				{
					"n": 31,
					"text": "And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these."
				},
				{
					"n": 32,
					"text": "And the scribe said unto him, Well, Master, thou hast said the truth: for there is one God; and there is none other but he:"
				},
				{
					"n": 33,
					"text": "And to love him with all the heart, and with all the understanding, and with all the soul, and with all the strength, and to love his neighbour as himself, is more than all whole burnt offerings and sacrifices."
				},
				{
					"n": 34,
					"text": "And when Jesus saw that he answered discreetly, he said unto him, Thou art not far from the kingdom of God. And no man after that durst ask him any question."
				}
			]
		},
		"luke.10.25-37": {
			"reference": "Luke 10:25-37",
			"verses": [
				{
					"n": 25,
					"text": "And, behold, a certain lawyer stood up, and tempted him, saying, Master, what shall I do to inherit eternal life?"
				},
				{
					"n": 26,
					"text": "He said unto him, What is written in the law? how readest thou?"
				},
				{
					"n": 27,
					"text": "And he answering said, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy strength, and with all thy mind; and thy neighbour as thyself."
				},
				{
					"n": 28,
					"text": "And he said unto him, Thou hast answered right: this do, and thou shalt live."
				},
				{
					"n": 29,
					"text": "But he, willing to justify himself, said unto Jesus, And who is my neighbour?"
				},
				{
					"n": 30,
					"text": "And Jesus answering said, A certain man went down from Jerusalem to Jericho, and fell among thieves, which stripped him of his raiment, and wounded him, and departed, leaving him half dead."
				},
				{
					"n": 31,
					"text": "And by chance there came down a certain priest that way: and when he saw him, he passed by on the other side."
				},
				{
					"n": 32,
					"text": "And likewise a Levite, when he was at the place, came and looked on him, and passed by on the other side."
				},
				{
					"n": 33,
					"text": "But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he had compassion on him,"
				},
				{
					"n": 34,
					"text": "And went to him, and bound up his wounds, pouring in oil and wine, and set him on his own beast, and brought him to an inn, and took care of him."
				},
				{
					"n": 35,
					"text": "And on the morrow when he departed, he took out two pence, and gave them to the host, and said unto him, Take care of him; and whatsoever thou spendest more, when I come again, I will repay thee."
				},
				{
					"n": 36,
					"text": "Which now of these three, thinkest thou, was neighbour unto him that fell among the thieves?"
				},
				{
					"n": 37,
					"text": "And he said, He that shewed mercy on him. Then said Jesus unto him, Go, and do thou likewise."
				}
			]
		},
		"john.13.34-35": {
			"reference": "John 13:34-35",
			"verses": [
				{
					"n": 34,
					"text": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another."
				},
				{
					"n": 35,
					"text": "By this shall all men know that ye are my disciples, if ye have love one to another."
				}
			]
		},
		"john.14.15": {
			"reference": "John 14:15",
			"verses": [
				{
					"n": 15,
					"text": "If ye love me, keep my commandments."
				}
			]
		},
		"matthew.22.40": {
			"reference": "Matthew 22:40",
			"verses": [
				{
					"n": 40,
					"text": "On these two commandments hang all the law and the prophets."
				}
			]
		},
		"matthew.22.37-40": {
			"reference": "Matthew 22:37-40",
			"verses": [
				{
					"n": 37,
					"text": "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."
				},
				{
					"n": 38,
					"text": "This is the first and great commandment."
				},
				{
					"n": 39,
					"text": "And the second is like unto it, Thou shalt love thy neighbour as thyself."
				},
				{
					"n": 40,
					"text": "On these two commandments hang all the law and the prophets."
				}
			]
		},
		"1timothy.6.11-16": {
			"reference": "1 Timothy 6:11-16",
			"verses": [
				{
					"n": 11,
					"text": "But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness."
				},
				{
					"n": 12,
					"text": "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses."
				},
				{
					"n": 13,
					"text": "I give thee charge in the sight of God, who quickeneth all things, and before Christ Jesus, who before Pontius Pilate witnessed a good confession;"
				},
				{
					"n": 14,
					"text": "That thou keep this commandment without spot, unrebukeable, until the appearing of our Lord Jesus Christ:"
				},
				{
					"n": 15,
					"text": "Which in his times he shall shew, who is the blessed and only Potentate, the King of kings, and Lord of lords;"
				},
				{
					"n": 16,
					"text": "Who only hath immortality, dwelling in the light which no man can approach unto; whom no man hath seen, nor can see: to whom be honour and power everlasting. Amen."
				}
			]
		},
		"matthew.5.43-48": {
			"reference": "Matthew 5:43-48",
			"verses": [
				{
					"n": 43,
					"text": "Ye have heard that it hath been said, Thou shalt love thy neighbour, and hate thine enemy."
				},
				{
					"n": 44,
					"text": "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;"
				},
				{
					"n": 45,
					"text": "That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust."
				},
				{
					"n": 46,
					"text": "For if ye love them which love you, what reward have ye? do not even the publicans the same?"
				},
				{
					"n": 47,
					"text": "And if ye salute your brethren only, what do ye more than others? do not even the publicans so?"
				},
				{
					"n": 48,
					"text": "Be ye therefore perfect, even as your Father which is in heaven is perfect."
				}
			]
		},
		"matthew.5.17-20": {
			"reference": "Matthew 5:17-20",
			"verses": [
				{
					"n": 17,
					"text": "Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil."
				},
				{
					"n": 18,
					"text": "For verily I say unto you, Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law, till all be fulfilled."
				},
				{
					"n": 19,
					"text": "Whosoever therefore shall break one of these least commandments, and shall teach men so, he shall be called the least in the kingdom of heaven: but whosoever shall do and teach them, the same shall be called great in the kingdom of heaven."
				},
				{
					"n": 20,
					"text": "For I say unto you, That except your righteousness shall exceed the righteousness of the scribes and Pharisees, ye shall in no case enter into the kingdom of heaven."
				}
			]
		},
		"john.15.9-17": {
			"reference": "John 15:9-17",
			"verses": [
				{
					"n": 9,
					"text": "As the Father hath loved me, so have I loved you: continue ye in my love."
				},
				{
					"n": 10,
					"text": "If ye keep my commandments, ye shall abide in my love; even as I have kept my Father’s commandments, and abide in his love."
				},
				{
					"n": 11,
					"text": "These things have I spoken unto you, that my joy might remain in you, and that your joy might be full."
				},
				{
					"n": 12,
					"text": "This is my commandment, That ye love one another, as I have loved you."
				},
				{
					"n": 13,
					"text": "Greater love hath no man than this, that a man lay down his life for his friends."
				},
				{
					"n": 14,
					"text": "Ye are my friends, if ye do whatsoever I command you."
				},
				{
					"n": 15,
					"text": "Henceforth I call you not servants; for the servant knoweth not what his lord doeth: but I have called you friends; for all things that I have heard of my Father I have made known unto you."
				},
				{
					"n": 16,
					"text": "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you."
				},
				{
					"n": 17,
					"text": "These things I command you, that ye love one another."
				}
			]
		},
		"romans.13.8-10": {
			"reference": "Romans 13:8-10",
			"verses": [
				{
					"n": 8,
					"text": "Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law."
				},
				{
					"n": 9,
					"text": "For this, Thou shalt not commit adultery, Thou shalt not kill, Thou shalt not steal, Thou shalt not bear false witness, Thou shalt not covet; and if there be any other commandment, it is briefly comprehended in this saying, namely, Thou shalt love thy neighbour as thyself."
				},
				{
					"n": 10,
					"text": "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law."
				}
			]
		},
		"galatians.5.13-14": {
			"reference": "Galatians 5:13-14",
			"verses": [
				{
					"n": 13,
					"text": "For, brethren, ye have been called unto liberty; only use not liberty for an occasion to the flesh, but by love serve one another."
				},
				{
					"n": 14,
					"text": "For all the law is fulfilled in one word, even in this; Thou shalt love thy neighbour as thyself."
				}
			]
		},
		"james.2.8": {
			"reference": "James 2:8",
			"verses": [
				{
					"n": 8,
					"text": "If ye fulfil the royal law according to the scripture, Thou shalt love thy neighbour as thyself, ye do well:"
				}
			]
		},
		"1john.4.7-12": {
			"reference": "1 John 4:7-12",
			"verses": [
				{
					"n": 7,
					"text": "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God."
				},
				{
					"n": 8,
					"text": "He that loveth not knoweth not God; for God is love."
				},
				{
					"n": 9,
					"text": "In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him."
				},
				{
					"n": 10,
					"text": "Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins."
				},
				{
					"n": 11,
					"text": "Beloved, if God so loved us, we ought also to love one another."
				},
				{
					"n": 12,
					"text": "No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us."
				}
			]
		},
		"1john.4.19-21": {
			"reference": "1 John 4:19-21",
			"verses": [
				{
					"n": 19,
					"text": "We love him, because he first loved us."
				},
				{
					"n": 20,
					"text": "If a man say, I love God, and hateth his brother, he is a liar: for he that loveth not his brother whom he hath seen, how can he love God whom he hath not seen?"
				},
				{
					"n": 21,
					"text": "And this commandment have we from him, That he who loveth God love his brother also."
				}
			]
		},
		"matthew.28.19-20": {
			"reference": "Matthew 28:19-20",
			"verses": [
				{
					"n": 19,
					"text": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:"
				},
				{
					"n": 20,
					"text": "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."
				}
			]
		},
		"mark.16.15": {
			"reference": "Mark 16:15",
			"verses": [
				{
					"n": 15,
					"text": "And he said unto them, Go ye into all the world, and preach the gospel to every creature."
				}
			]
		}
	},
	"asv": {
		"matthew.22.36-40": {
			"reference": "Matthew 22:36-40",
			"verses": [
				{
					"n": 36,
					"text": "Teacher, which is the great commandment in the law?"
				},
				{
					"n": 37,
					"text": "And he said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."
				},
				{
					"n": 38,
					"text": "This is the great and first commandment."
				},
				{
					"n": 39,
					"text": "And a second like [unto it] is this, Thou shalt love thy neighbor as thyself."
				},
				{
					"n": 40,
					"text": "On these two commandments the whole law hangeth, and the prophets."
				}
			]
		},
		"mark.12.28-34": {
			"reference": "Mark 12:28-34",
			"verses": [
				{
					"n": 28,
					"text": "And one of the scribes came, and heard them questioning together, and knowing that he had answered them well, asked him, What commandment is the first of all?"
				},
				{
					"n": 29,
					"text": "Jesus answered, The first is, Hear, O Israel; The Lord our God, the Lord is one:"
				},
				{
					"n": 30,
					"text": "and thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength."
				},
				{
					"n": 31,
					"text": "The second is this, Thou shalt love thy neighbor as thyself. There is none other commandment greater than these."
				},
				{
					"n": 32,
					"text": "And the scribe said unto him, Of a truth, Teacher, thou hast well said that he is one; and there is none other but he:"
				},
				{
					"n": 33,
					"text": "and to love him with all the heart, and with all the understanding, and with all the strength, and to love his neighbor as himself, is much more than all whole burnt-offerings and sacrifices."
				},
				{
					"n": 34,
					"text": "And when Jesus saw that he answered discreetly, he said unto him, Thou art not far from the kingdom of God. And no man after that durst ask him any question."
				}
			]
		},
		"luke.10.25-37": {
			"reference": "Luke 10:25-37",
			"verses": [
				{
					"n": 25,
					"text": "And behold, a certain lawyer stood up and made trial of him, saying, Teacher, what shall I do to inherit eternal life?"
				},
				{
					"n": 26,
					"text": "And he said unto him, What is written in the law? how readest thou?"
				},
				{
					"n": 27,
					"text": "And he answering said, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy strength, and with all thy mind; and thy neighbor as thyself."
				},
				{
					"n": 28,
					"text": "And he said unto him, Thou hast answered right: this do, and thou shalt live."
				},
				{
					"n": 29,
					"text": "But he, desiring to justify himself, said unto Jesus, And who is my neighbor?"
				},
				{
					"n": 30,
					"text": "Jesus made answer and said, A certain man was going down from Jerusalem to Jericho; and he fell among robbers, who both stripped him and beat him, and departed, leaving him half dead."
				},
				{
					"n": 31,
					"text": "And by chance a certain priest was going down that way: and when he saw him, he passed by on the other side."
				},
				{
					"n": 32,
					"text": "And in like manner a Levite also, when he came to the place, and saw him, passed by on the other side."
				},
				{
					"n": 33,
					"text": "But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he was moved with compassion,"
				},
				{
					"n": 34,
					"text": "and came to him, and bound up his wounds, pouring on [them] oil and wine; and he set him on his own beast, and brought him to an inn, and took care of him."
				},
				{
					"n": 35,
					"text": "And on the morrow he took out two shillings, and gave them to the host, and said, Take care of him; and whatsoever thou spendest more, I, when I come back again, will repay thee."
				},
				{
					"n": 36,
					"text": "Which of these three, thinkest thou, proved neighbor unto him that fell among the robbers?"
				},
				{
					"n": 37,
					"text": "And he said, He that showed mercy on him. And Jesus said unto him, Go, and do thou likewise."
				}
			]
		},
		"john.13.34-35": {
			"reference": "John 13:34-35",
			"verses": [
				{
					"n": 34,
					"text": "A new commandment I give unto you, that ye love one another; even as I have loved you, that ye also love one another."
				},
				{
					"n": 35,
					"text": "By this shall all men know that ye are my disciples, if ye have love one to another."
				}
			]
		},
		"john.14.15": {
			"reference": "John 14:15",
			"verses": [
				{
					"n": 15,
					"text": "If ye love me, ye will keep my commandments."
				}
			]
		},
		"matthew.22.40": {
			"reference": "Matthew 22:40",
			"verses": [
				{
					"n": 40,
					"text": "On these two commandments the whole law hangeth, and the prophets."
				}
			]
		},
		"matthew.22.37-40": {
			"reference": "Matthew 22:37-40",
			"verses": [
				{
					"n": 37,
					"text": "And he said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."
				},
				{
					"n": 38,
					"text": "This is the great and first commandment."
				},
				{
					"n": 39,
					"text": "And a second like [unto it] is this, Thou shalt love thy neighbor as thyself."
				},
				{
					"n": 40,
					"text": "On these two commandments the whole law hangeth, and the prophets."
				}
			]
		},
		"1timothy.6.11-16": {
			"reference": "1 Timothy 6:11-16",
			"verses": [
				{
					"n": 11,
					"text": "But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness."
				},
				{
					"n": 12,
					"text": "Fight the good fight of the faith, lay hold on the life eternal, whereunto thou wast called, and didst confess the good confession in the sight of many witnesses."
				},
				{
					"n": 13,
					"text": "I charge thee in the sight of God, who giveth life to all things, and of Christ Jesus, who before Pontius Pilate witnessed the good confession;"
				},
				{
					"n": 14,
					"text": "that thou keep the commandment, without spot, without reproach, until the appearing of our Lord Jesus Christ:"
				},
				{
					"n": 15,
					"text": "which in its own times he shall show, who is the blessed and only Potentate, the King of kings, and Lord of lords;"
				},
				{
					"n": 16,
					"text": "who only hath immortality, dwelling in light unapproachable; whom no man hath seen, nor can see: to whom [be] honor and power eternal. Amen."
				}
			]
		},
		"matthew.5.43-48": {
			"reference": "Matthew 5:43-48",
			"verses": [
				{
					"n": 43,
					"text": "Ye have heard that it was said, Thou shalt love thy neighbor, and hate thine enemy:"
				},
				{
					"n": 44,
					"text": "but I say unto you, love your enemies, and pray for them that persecute you;"
				},
				{
					"n": 45,
					"text": "that ye may be sons of your Father who is in heaven: for he maketh his sun to rise on the evil and the good, and sendeth rain on the just and the unjust."
				},
				{
					"n": 46,
					"text": "For if ye love them that love you, what reward have ye? do not even the publicans the same?"
				},
				{
					"n": 47,
					"text": "And if ye salute your brethren only, what do ye more [than others?] do not even the Gentiles the same?"
				},
				{
					"n": 48,
					"text": "Ye therefore shall be perfect, as your heavenly Father is perfect."
				}
			]
		},
		"matthew.5.17-20": {
			"reference": "Matthew 5:17-20",
			"verses": [
				{
					"n": 17,
					"text": "Think not that I came to destroy the law or the prophets: I came not to destroy, but to fulfil."
				},
				{
					"n": 18,
					"text": "For verily I say unto you, Till heaven and earth pass away, one jot or one tittle shall in no wise pass away from the law, till all things be accomplished."
				},
				{
					"n": 19,
					"text": "Whosoever therefore shall break one of these least commandments, and shall teach men so, shall be called least in the kingdom of heaven: but whosoever shall do and teach them, he shall be called great in the kingdom of heaven."
				},
				{
					"n": 20,
					"text": "For I say unto you, that except your righteousness shall exceed [the righteousness] of the scribes and Pharisees, ye shall in no wise enter into the kingdom of heaven."
				}
			]
		},
		"john.15.9-17": {
			"reference": "John 15:9-17",
			"verses": [
				{
					"n": 9,
					"text": "Even as the Father hath loved me, I also have loved you: abide ye in my love."
				},
				{
					"n": 10,
					"text": "If ye keep my commandments, ye shall abide in my love; even as I have kept my Father`s commandments, and abide in his love."
				},
				{
					"n": 11,
					"text": "These things have I spoken unto you, that my joy may be in you, and [that] your joy may be made full."
				},
				{
					"n": 12,
					"text": "This is my commandment, that ye love one another, even as I have loved you."
				},
				{
					"n": 13,
					"text": "Greater love hath no man than this, that a man lay down his life for his friends."
				},
				{
					"n": 14,
					"text": "Ye are my friends, if ye do the things which I command you."
				},
				{
					"n": 15,
					"text": "No longer do I call you servants; for the servant knoweth not what his lord doeth: but I have called you friends; for all things that I heard from my Father, I have made known unto you."
				},
				{
					"n": 16,
					"text": "Ye did not choose me, but I chose you, and appointed you, that ye should go and bear fruit, and [that] your fruit should abide: that whatsoever ye shall ask of the Father in my name, he may give it you."
				},
				{
					"n": 17,
					"text": "These things I command you, that ye may love one another."
				}
			]
		},
		"romans.13.8-10": {
			"reference": "Romans 13:8-10",
			"verses": [
				{
					"n": 8,
					"text": "Owe no man anything, save to love one another: for he that loveth his neighbor hath fulfilled the law."
				},
				{
					"n": 9,
					"text": "For this, Thou shalt not commit adultery, Thou shalt not kill, Thou shalt not steal, Thou shalt not covet, and if there be any other commandment, it is summed up in this word, namely, Thou shalt love thy neighbor as thyself."
				},
				{
					"n": 10,
					"text": "Love worketh no ill to his neighbor: love therefore is the fulfilment of the law."
				}
			]
		},
		"galatians.5.13-14": {
			"reference": "Galatians 5:13-14",
			"verses": [
				{
					"n": 13,
					"text": "For ye, brethren, were called for freedom; only [use] not your freedom for an occasion to the flesh, but through love be servants one to another."
				},
				{
					"n": 14,
					"text": "For the whole law is fulfilled in one word, [even] in this: Thou shalt love thy neighbor as thyself."
				}
			]
		},
		"james.2.8": {
			"reference": "James 2:8",
			"verses": [
				{
					"n": 8,
					"text": "Howbeit if ye fulfil the royal law, according to the scripture, Thou shalt love thy neighbor as thyself, ye do well:"
				}
			]
		},
		"1john.4.7-12": {
			"reference": "1 John 4:7-12",
			"verses": [
				{
					"n": 7,
					"text": "Beloved, let us love one another: for love is of God; and every one that loveth is begotten of God, and knoweth God."
				},
				{
					"n": 8,
					"text": "He that loveth not knoweth not God; for God is love."
				},
				{
					"n": 9,
					"text": "Herein was the love of God manifested in us, that God hath sent his only begotten Son into the world that we might live through him."
				},
				{
					"n": 10,
					"text": "Herein is love, not that we loved God, but that he loved us, and sent his Son [to be] the propitiation for our sins."
				},
				{
					"n": 11,
					"text": "Beloved, if God so loved us, we also ought to love one another."
				},
				{
					"n": 12,
					"text": "No man hath beheld God at any time: if we love one another, God abideth in us, and his love is perfected in us:"
				}
			]
		},
		"1john.4.19-21": {
			"reference": "1 John 4:19-21",
			"verses": [
				{
					"n": 19,
					"text": "We love, because he first loved us."
				},
				{
					"n": 20,
					"text": "If a man say, I love God, and hateth his brother, he is a liar: for he that loveth not his brother whom he hath seen, cannot love God whom he hath not seen."
				},
				{
					"n": 21,
					"text": "And this commandment have we from him, that he who loveth God love his brother also."
				}
			]
		},
		"matthew.28.19-20": {
			"reference": "Matthew 28:19-20",
			"verses": [
				{
					"n": 19,
					"text": "Go ye therefore, and make disciples of all the nations, baptizing them into the name of the Father and of the Son and of the Holy Spirit:"
				},
				{
					"n": 20,
					"text": "teaching them to observe all things whatsoever I commanded you: and lo, I am with you always, even unto the end of the world."
				}
			]
		},
		"mark.16.15": {
			"reference": "Mark 16:15",
			"verses": [
				{
					"n": 15,
					"text": "And he said unto them, Go ye into all the world, and preach the gospel to the whole creation."
				}
			]
		}
	}
};
