#!/usr/bin/env node
/* ========================================================================== */
/* Build hoa-custom.v2.css from hoa-custom.css — an EXPERIMENT, not a replace */
/*  1. drop exact-duplicate rule blocks (same selector + same body), keep 1st  */
/*  2. wrap everything after the @import in `@layer westbrooke { … }`          */
/* Nothing else changes: same selectors, same declarations, same !importants. */
/* Output: custom-css/hoa-custom.v2.css + public copy for runtime A/B.        */
/* ========================================================================== */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'custom-css/hoa-custom.css'), 'utf8');

/* pull @import lines to the top (they must precede any @layer block) */
const imports = [...src.matchAll(/^@import[^\n]*\n/gm)].map(m => m[0]);
let body = src.replace(/^@import[^\n]*\n/gm, '');

/* split into top-level blocks by brace depth, tracking comments as their own chunks */
const blocks = [];
let depth = 0, start = 0, i = 0;
while (i < body.length) {
	const ch = body[i];
	if (ch === '/' && body[i + 1] === '*') { const end = body.indexOf('*/', i + 2); i = end === -1 ? body.length : end + 2; continue; }
	if (ch === '"' || ch === "'") { const q = ch; i++; while (i < body.length && body[i] !== q) { if (body[i] === '\\') i++; i++; } i++; continue; }
	if (ch === '{') depth++;
	if (ch === '}') { depth--; if (depth === 0) { blocks.push(body.slice(start, i + 1)); start = i + 1; } }
	i++;
}
const tail = body.slice(start);

/* dedupe: normalise whitespace; identical selector+body → keep the first */
const seen = new Set(); let dropped = 0;
const kept = blocks.filter(b => {
	const key = b.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').trim();
	if (!key.includes('{')) return true;
	if (seen.has(key)) { dropped++; return false; }
	seen.add(key); return true;
});

const out = `${imports.join('')}
/* ========================================================================== */
/* hoa-custom.v2.css — GENERATED by scripts/build-css-v2.mjs from hoa-custom  */
/* .css. Experiment: ${dropped} duplicate block(s) removed; everything wrapped */
/* in @layer westbrooke. Do not hand-edit; edit hoa-custom.css and rebuild.    */
/* ========================================================================== */
@layer westbrooke {
${kept.join('')}${tail}
}
`;
writeFileSync(join(root, 'custom-css/hoa-custom.v2.css'), out);
mkdirSync(join(root, 'public/westbrookeplacehoa/custom-css'), { recursive: true });
writeFileSync(join(root, 'public/westbrookeplacehoa/custom-css/hoa-custom.v2.css'), out);
console.log(`v2: ${kept.length} blocks kept, ${dropped} duplicates dropped, ${out.length} bytes (v1 ${src.length})`);
